### ISSUE TITLE
Disable creating new issues for this repository

### ISSUE THREAD

**Issue by faiq** [npm/npm-www#966]
I think it would be best if we close any new issues from being open in this repository, because its deprecated.

**Comment by zeke** [comment]
Good idea. Is there a way to disable issue creation without removing all the old issues? This checkbox doesn't really make it clear what will happen to existing issues if I disable it:

![screen shot 2015-01-05 at 10 30 03 am](https://cloud.githubusercontent.com/assets/2289/5617696/54cbd80c-94c6-11e4-9afd-9c21881b2b12.png)

**Comment by faiq** [comment]
i just sent a support email out, i'll let you know the answer to that as soon as they get back to me.

**Comment by zeke** [comment]
I did too!
