### ISSUE TITLE
Download statistics not working

### ISSUE THREAD

**Issue by vitaly-t** [npm/npm-www#970]
My package, [pg-promise](https://www.npmjs.com/package/pg-promise), has been showing 0 weekly downloads in NPM search results for 2 weeks now, even though it never had 0 daily downloads in its entire history.

When I look at [the package details](https://www.npmjs.com/package/pg-promise), it shows the correct statistics, but when I find it [in the search results](https://www.npmjs.com/search?q=pg-promise), it is always 0 weekly downloads.

Any idea how this is possible?

**Comment by KenanY** [comment]
@vitaly-t This repository is for the old code that ran the website. Any current issues should be opened at [npm/newww](https://github.com/npm/newww).

**Comment by vitaly-t** [comment]
Thanks!
