### ISSUE TITLE
Relative GH image in Readme not being re-written as absolute

### ISSUE THREAD

**Issue by techninja** [npm/npm-www#974]
I saw #717 and it seems like its test case is working, but this doesn't? Very strange.

https://www.npmjs.com/package/robopaint-mode-example
VS
https://github.com/techninja/robopaint-mode-example

**Comment by KenanY** [comment]
@techninja Could you please move this to [newww](https://github.com/npm/newww)?

**Comment by techninja** [comment]
Sure thing.
